#
# Reimport all builds on an already deployed branch
#
- name: "{{ branch }} - Wait for deployment"
  uri:
    url: "http://{{ config.scenariooHost }}/scenarioo-{{ branch }}"
    status_code: 200
  register: result
  until: result.status == 200
  delay: 3
  retries: 60
  when: lookup('env', 'ENVIRONMENT') != 'dev'   # Because would fail when using vagrant

- name: "{{ branch }} - Trigger reimport of builds"
  uri:
    url: "http://{{ config.scenariooHost }}/scenarioo-{{ branch }}/rest/builds/updateAndImport"
    status_code: 200,204
  when: lookup('env', 'ENVIRONMENT') != 'dev'   # Because would fail when using vagrant

- name: "{{ branch }} - Wait for Imports to finish"
  uri:
    url: "http://{{ config.scenariooHost }}/scenarioo-{{ branch }}/rest/builds/importsAndComparisonCalculationsFinished"
    return_content: yes
  register: this
  until: "'true' in this.content"
  delay: 3
  retries: 60
  when: lookup('env', 'ENVIRONMENT') != 'dev'   # Because would fail when using vagrant

