version: 2
jobs:
  deploy:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/python:3.6-jessie-node-browsers
    working_directory: ~/infra
    steps:
          - checkout
          # Add keys of AWS host
          - add_ssh_keys:
                fingerprints:
                  - "ab:ce:2a:8f:f2:7a:82:93:de:d4:20:95:62:53:71:70"
          - run:
              name: Install ansible # Maybe pip install ansible?
              command: |
                sudo pip install ansible --quiet
          - run:
              name: Deploy server
              command: |
                export ANSIBLE_HOST_KEY_CHECKING=False    # TODO: Add known_hosts to repository
                ansible-playbook ./site.yml -i ./hosts/hosts_aws

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - deploy:
          # Get environment vars: https://circleci.com/docs/2.0/contexts/
          context: Scenarioo
          filters:
            branches:
              only: master  # Avoid deployment being triggered for PRs

