version: 2
jobs:
  deploy:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/infra
    steps:
          - checkout
          # Add keys of AWS host
          - add_ssh_keys:
                fingerprints:
                  - "29:5a:f5:86:2d:e0:60:e1:7f:22:7c:0e:ad:2b:1c:40"
          - run:
              name: Install ansible # Maybe pip install ansible?
              command: |
                sudo /bin/su -c "echo \"deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main\" >> /etc/apt/sources.list"
                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
                sudo apt-get update -yq
                sudo apt-get install ansible -yq
          - run:
              name: Deploy server
              command: |
                export ANSIBLE_HOST_KEY_CHECKING=False    # TODO: Add known_hosts to repository
                ansible-playbook ./site.yml -i ./hosts/hosts_aws

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - deploy:
          # Get environment vars: https://circleci.com/docs/2.0/contexts/
          context: scenarioo
