version: 2
jobs:
  deploy:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/python:3.6-jessie-node-browsers
    working_directory: ~/infra
    steps:
          - checkout
          # Add keys of OVH host: https://circleci.com/gh/scenarioo/scenarioo-infrastructure/edit#ssh
          - add_ssh_keys:
                fingerprints:
                  - "61:98:9a:30:06:78:1e:34:a3:43:86:69:9d:42:5a:0b"
          - run:
              name: Install ansible
              command: sudo pip install 'ansible==2.5' --quiet
          - run:
              name: Install jq
              command: sudo pip install 'jq==1.0.0' --quiet
          - run:
              name: Deploy server
              command: |
                export ANSIBLE_HOST_KEY_CHECKING=False    # TODO: Add known_hosts to repository
                bash ./.circleci/do-exclusively.sh ansible-playbook ./site.yml -i ./hosts/hosts_demoserver_ovh
  test_scripts:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/python:3.6-jessie-node-browsers
    working_directory: ~/infra
    steps:
          - checkout
          - run:
              name: Install bats
              command: sudo apt-get install bats
          - run:
              name: Run tests
              command: bats tests/

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      # temporarily disable test_scripts
      #- test_scripts
      - deploy:
          #requires:
           # - test_scripts
          # Get environment vars: https://circleci.com/docs/2.0/contexts/
          context: Scenarioo    # https://circleci.com/gh/organizations/scenarioo/settings#contexts
          filters:
            branches:
              only: master  # Avoid deployment being triggered for PRs
