version: 2
jobs:
  deploy:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/infra
    steps:
          - checkout

          # Add keys of AWS host
          - add_ssh_keys:
                fingerprints:
                  - "29:5a:f5:86:2d:e0:60:e1:7f:22:7c:0e:ad:2b:1c:40"
          - run:
              name: Install ansible
              command: |
                sudo apt-get install software-properties-common -yqq
                sudo apt-add-repository ppa:ansible/ansible -yqq
                sudo apt-get update -yqq
                sudo apt-get install ansible -yqq
          - run:
              name: Deploy server
              command: ansible-playbook ./site.yml -i ./ansible/hosts_aws

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
          # Get environment vars: https://circleci.com/docs/2.0/contexts/
          context: scenarioo
