# See: https://devtidbits.com/2015/12/08/nginx-as-a-reverse-proxy-to-apache-tomcat/
nginx_vhosts:
  - listen: 80
    server_name: demo.scenarioo.org scenarioo.cgross-aws.de localhost
    extra_parameters: |
      location /overview {
        index index.html;
        alias /scenarioo/overviewpage;
        try_files $uri $uri/ =404;
      }
      location / {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
      }