#
# Installs and configures tomcat8
#
- name: Install tomcat 8
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - tomcat8
      - tomcat8-admin

- name: Copy server.xml
  copy:
    src: server.xml
    dest: "{{ config.tomcatFolder }}/conf"
  notify: Restart tomcat

- name: Copy tomcat-users.xml
  # only needed for scenarioo 4.0 and earlier (will be removed in 5.0)
  template:
    src: tomcat-users.xml.j2
    dest: "{{ config.tomcatFolder }}/conf/tomcat-users.xml"
  notify: Restart tomcat
  no_log: true  # Don't show TOMCAT_USER_PASSWORD

- name: Copy setenv.sh for memory settings
  copy:
    src: setenv.sh
    dest: /usr/share/tomcat8/bin
  notify: Restart tomcat

- name: Restart tomcat every night at 2:30
  cron:
    name: "Restart tomcat every night"
    minute: 30
    hour: 2
    job: "systemctl restart tomcat8 > /dev/null"

# Run handlers now => e.g. restart tomcat at this point if needed
- meta: flush_handlers
