#
# Installs docker and runs desired containers (e.g. elasticsearch)
#
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install docker & dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python3-pip

- name: Install pip docker package
  pip: name=docker

# https://github.com/docker-library/elasticsearch/issues/111
- name: Set sysctl vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Running elasticsearch
  docker_container:
    name: elasticsearch-5
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    state: started
    restart: yes
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    env:
      cluster.name: elasticsearch
      xpack.ml.enabled: "false"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m

- file: path=/docker/netdata/overrides/python.d state=directory
- name: Copy netdata config
  copy:
    src: netdata/overrides
    dest: /docker/netdata

- name: Run netdata
  docker_container:
    name: netdata
    image: titpetric/netdata:1.8
    state: started
    ports:
      - "127.0.0.1:19999:19999"
    capabilities:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /docker/netdata/overrides:/etc/netdata/override